// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TetrioStats.Data.Context;

namespace TetrioStats.Data.Migrations
{
	[DbContext(typeof(CoreContext))]
	class CoreContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("ProductVersion", "3.1.17");

			modelBuilder.Entity("TetrioStats.Data.Domain.GameRecord", b =>
					{
						b.Property<int>("GameRecordID")
											.ValueGeneratedOnAdd()
											.HasColumnType("INTEGER");

						b.Property<int>("BTB")
											.HasColumnType("INTEGER");

						b.Property<int>("Combo")
											.HasColumnType("INTEGER");

						b.Property<int?>("CurrentComboPower")
											.HasColumnType("INTEGER");

						b.Property<TimeSpan>("FinalTime")
											.HasColumnType("TEXT");

						b.Property<int>("FinesseCombo")
											.HasColumnType("INTEGER");

						b.Property<int>("FinesseFaults")
											.HasColumnType("INTEGER");

						b.Property<int>("FinessePerfectPieces")
											.HasColumnType("INTEGER");

						b.Property<int>("GameType")
											.HasColumnType("INTEGER");

						b.Property<int>("GarbageAttack")
											.HasColumnType("INTEGER");

						b.Property<int>("GarbageTotalCleared")
											.HasColumnType("INTEGER");

						b.Property<int>("GarbageTotalReceived")
											.HasColumnType("INTEGER");

						b.Property<int>("GarbageTotalSent")
											.HasColumnType("INTEGER");

						b.Property<int>("Holds")
											.HasColumnType("INTEGER");

						b.Property<int>("Inputs")
											.HasColumnType("INTEGER");

						b.Property<bool>("IsMultiplayer")
											.HasColumnType("INTEGER");

						b.Property<int>("Kills")
											.HasColumnType("INTEGER");

						b.Property<int>("Level")
											.HasColumnType("INTEGER");

						b.Property<int>("LevelLines")
											.HasColumnType("INTEGER");

						b.Property<int>("LevelLinesNeeded")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsAllClears")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsDoubles")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsMiniTSpinDoubles")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsMiniTSpinSingles")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsMiniTSpins")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsQuads")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsRealTSpins")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsSingles")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsTSpinDoubles")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsTSpinQuads")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsTSpinSingles")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsTSpinTriples")
											.HasColumnType("INTEGER");

						b.Property<int>("LineClearsTriples")
											.HasColumnType("INTEGER");

						b.Property<int>("LinesCleared")
											.HasColumnType("INTEGER");

						b.Property<string>("ReplayID")
											.IsRequired()
											.HasColumnType("TEXT");

						b.Property<int>("Score")
											.HasColumnType("INTEGER");

						b.Property<string>("StreamKey")
											.IsRequired()
											.HasColumnType("TEXT");

						b.Property<int>("TSpins")
											.HasColumnType("INTEGER");

						b.Property<string>("TetrioGameRecordID")
											.IsRequired()
											.HasColumnType("TEXT");

						b.Property<DateTime>("TimeStamp")
											.HasColumnType("TEXT");

						b.Property<int>("TopBTB")
											.HasColumnType("INTEGER");

						b.Property<int>("TopCombo")
											.HasColumnType("INTEGER");

						b.Property<int>("TotalPiecesPlaced")
											.HasColumnType("INTEGER");

						b.Property<int>("UserID")
											.HasColumnType("INTEGER");

						b.Property<string>("Username")
											.IsRequired()
											.HasColumnType("TEXT");

						b.Property<int>("ZenLevel")
											.HasColumnType("INTEGER");

						b.Property<int>("ZenProgress")
											.HasColumnType("INTEGER");

						b.HasKey("GameRecordID");

						b.HasIndex("UserID");

						b.ToTable("GameRecords");
					});

			modelBuilder.Entity("TetrioStats.Data.Domain.User", b =>
					{
						b.Property<int>("UserID")
											.ValueGeneratedOnAdd()
											.HasColumnType("INTEGER");

						b.Property<string>("TetrioUserID")
											.IsRequired()
											.HasColumnType("TEXT")
											.IsFixedLength(true)
											.HasMaxLength(24);

						b.Property<string>("Username")
											.IsRequired()
											.HasColumnType("TEXT")
											.HasMaxLength(16);

						b.HasKey("UserID");

						b.HasIndex("TetrioUserID")
											.IsUnique();

						b.HasIndex("Username")
											.IsUnique();

						b.ToTable("Users");
					});

			modelBuilder.Entity("TetrioStats.Data.Domain.UserStatisticsEntry", b =>
					{
						b.Property<int>("UserStatisticsEntryID")
											.ValueGeneratedOnAdd()
											.HasColumnType("INTEGER");

						b.Property<double>("AverageRollingAPM")
											.HasColumnName("APM")
											.HasColumnType("REAL");

						b.Property<double>("AverageRollingPPS")
											.HasColumnName("PPS")
											.HasColumnType("REAL");

						b.Property<double>("AverageRollingVsScore")
											.HasColumnName("VS")
											.HasColumnType("REAL");

						b.Property<int>("GamesPlayed")
											.HasColumnType("INTEGER");

						b.Property<int>("GamesWon")
											.HasColumnType("INTEGER");

						b.Property<double>("GlickoRating")
											.HasColumnName("Glicko")
											.HasColumnType("REAL");

						b.Property<double>("GlickoRatingDeviation")
											.HasColumnName("GlickoRD")
											.HasColumnType("REAL");

						b.Property<int>("GlobalLeaderBoardsStanding")
											.HasColumnName("GlobalStanding")
											.HasColumnType("INTEGER");

						b.Property<int>("LocalLeaderBoardsStanding")
											.HasColumnName("LocalStanding")
											.HasColumnType("INTEGER");

						b.Property<double>("Percentile")
											.HasColumnType("REAL");

						b.Property<string>("PercentileRank")
											.IsRequired()
											.HasColumnType("TEXT");

						b.Property<int>("TetraLeagueGamesPlayed")
											.HasColumnName("TetraGamesPlayed")
											.HasColumnType("INTEGER");

						b.Property<int>("TetraLeagueGamesWon")
											.HasColumnName("TetraGamesWon")
											.HasColumnType("INTEGER");

						b.Property<double>("TetraLeagueRating")
											.HasColumnName("TR")
											.HasColumnType("REAL");

						b.Property<DateTime>("TimeStamp")
											.HasColumnType("TEXT");

						b.Property<TimeSpan>("TotalGamePlayDuration")
											.HasColumnName("GamePlayTime")
											.HasColumnType("TEXT");

						b.Property<int>("UserID")
											.HasColumnType("INTEGER");

						b.Property<string>("UserRank")
											.IsRequired()
											.HasColumnName("Rank")
											.HasColumnType("TEXT");

						b.Property<double>("XP")
											.HasColumnType("REAL");

						b.HasKey("UserStatisticsEntryID");

						b.HasIndex("UserID");

						b.ToTable("UserStatisticsEntries");
					});

			modelBuilder.Entity("TetrioStats.Data.Domain.GameRecord", b =>
					{
						b.HasOne("TetrioStats.Data.Domain.User", "User")
											.WithMany()
											.HasForeignKey("UserID")
											.OnDelete(DeleteBehavior.Cascade)
											.IsRequired();
					});

			modelBuilder.Entity("TetrioStats.Data.Domain.UserStatisticsEntry", b =>
					{
						b.HasOne("TetrioStats.Data.Domain.User", "User")
											.WithMany()
											.HasForeignKey("UserID")
											.OnDelete(DeleteBehavior.Cascade)
											.IsRequired();
					});
#pragma warning restore 612, 618
		}
	}
}